# Generated by Django 5.0 on 2023-12-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customuser_surname_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
    ]
