# Generated by Django 4.2.7 on 2023-12-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_post_image'),
    ]

    operations = [
    ]
